### ISSUE TITLE
Bun.sh integration

### ISSUE THREAD

**Issue by philosofonusus** [zookyy/crypto-sniper#6]
Hello, I have your premium version I would like to use it with bun, I face this issue, can you please help me if I could resolve this?
```
 error: Cannot find module 'crypto'
 code: "MODULE_NOT_FOUND"

      at Q (/Users/daisydream/Projects/CryptoSniper/index.js:163:32)
      at /Users/daisydream/Projects/CryptoSniper/index.js:352:28
      at Q (/Users/daisydream/Projects/CryptoSniper/index.js:169:20)
      at x (/Users/daisydream/Projects/CryptoSniper/index.js:189:126)
      at /Users/daisydream/Projects/CryptoSniper/index.js:193:7
```

**Comment by zookyy** [comment]
Hey, you need to run npm install in the dir of the bot.

**Comment by philosofonusus** [comment]
> Hey, you need to run npm install in the dir of the bot.

Crypto is built-in module of nodejs, so it won't do much, I'm trying to add more speed to it with bun, bun has its own similar module like crypto, maybe you could make the bot work with bun?

**Comment by philosofonusus** [comment]
That's more like a feature which will provide a lot more performance than basic nodejs based on benchmarks

**Comment by zookyy** [comment]
Well the demo bot is a plain simple bot that executes a buy transaction. I'm not planning to add any other functionality to it than that.
